config/routes.rb
Rails.application.routes.draw do
  get "new", to: "games#new"
  post "score", to: "games#score"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController

  def new
    @letters = generate_grid(10).join
  end

  def score
    @letters = params[:letters].split('')
    @attempt = params[:attempt]
    @result = run_game(@attempt, @letters)
  end

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end

  def included?(guess, letters)
    guess.split('').all? { |letter| letters.include? letter }
  end

  def compute_score(attempt)
    attempt.size
  end

  def run_game(attempt, letters)
    result = {}
    result[:word] = valid_word(attempt)
    result[:score], result[:message] = score_and_message(attempt, letters, result[:word])
    result
  end

  def score_and_message(attempt, letters, word)
    if word
      if included?(attempt.upcase, letters)
        score = compute_score(attempt)
        [score, 'Well done!']
      else
        [0, 'Word not on the grid.']
      end
    else
      [0, 'Not an English word']
    end
  end

  def valid_word(word)
    response = URI.open("https://wagon-dictionary.herokuapp.com/#{word.downcase}")
    json = JSON.parse(response.read.to_s)
    json['found'] unless json['Error']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>WELCOME TO THE LONGEST WORD GAME</h1>

<h2>Grid: <%= @letters %></h2>

<form action="<%= score_url %>" method="post" data-turbo='false'>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="attempt">
  <input type="hidden" name="letters" value="<%= @letters %>">
  <input type="submit" value="GO">
</form>

app/views/games/score.html.erb
<h1>Your result</h1>

<ul>
  <li>Attempt: <%= @attempt%></li>
  <li>Word: <%= @result[:word]%></li>
  <li>Message: <%= @result[:message]%></li>
  <li>Score: <%= @result[:score]%></li>
</ul>

<%= link_to("Restart", new_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>